"""create initial tables

Revision ID: de31743c9111
Revises: 
Create Date: 2026-01-11 17:40:18.055794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de31743c9111'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operacoes_comex', 'razao_social_importador',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('operacoes_comex', 'razao_social_exportador',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_operacoes_comex_cnpj_exportador'), 'operacoes_comex', ['cnpj_exportador'], unique=False)
    op.create_index(op.f('ix_operacoes_comex_cnpj_importador'), 'operacoes_comex', ['cnpj_importador'], unique=False)
    op.create_index(op.f('ix_operacoes_comex_razao_social_exportador'), 'operacoes_comex', ['razao_social_exportador'], unique=False)
    op.create_index(op.f('ix_operacoes_comex_razao_social_importador'), 'operacoes_comex', ['razao_social_importador'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operacoes_comex_razao_social_importador'), table_name='operacoes_comex')
    op.drop_index(op.f('ix_operacoes_comex_razao_social_exportador'), table_name='operacoes_comex')
    op.drop_index(op.f('ix_operacoes_comex_cnpj_importador'), table_name='operacoes_comex')
    op.drop_index(op.f('ix_operacoes_comex_cnpj_exportador'), table_name='operacoes_comex')
    op.alter_column('operacoes_comex', 'razao_social_exportador',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('operacoes_comex', 'razao_social_importador',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
