"""create initial tables

Revision ID: de31743c9111
Revises: 
Create Date: 2026-01-11 17:40:18.055794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'de31743c9111'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def index_exists(table_name: str, index_name: str) -> bool:
    """Verifica se um índice já existe na tabela."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alterar colunas apenas se necessário (pode falhar se já foram alteradas)
    try:
        op.alter_column('operacoes_comex', 'razao_social_importador',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    except Exception:
        pass  # Coluna já pode estar no formato correto
    
    try:
        op.alter_column('operacoes_comex', 'razao_social_exportador',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    except Exception:
        pass  # Coluna já pode estar no formato correto
    
    # Criar índices apenas se não existirem
    if not index_exists('operacoes_comex', 'ix_operacoes_comex_cnpj_exportador'):
        op.create_index(op.f('ix_operacoes_comex_cnpj_exportador'), 'operacoes_comex', ['cnpj_exportador'], unique=False)
    
    if not index_exists('operacoes_comex', 'ix_operacoes_comex_cnpj_importador'):
        op.create_index(op.f('ix_operacoes_comex_cnpj_importador'), 'operacoes_comex', ['cnpj_importador'], unique=False)
    
    if not index_exists('operacoes_comex', 'ix_operacoes_comex_razao_social_exportador'):
        op.create_index(op.f('ix_operacoes_comex_razao_social_exportador'), 'operacoes_comex', ['razao_social_exportador'], unique=False)
    
    if not index_exists('operacoes_comex', 'ix_operacoes_comex_razao_social_importador'):
        op.create_index(op.f('ix_operacoes_comex_razao_social_importador'), 'operacoes_comex', ['razao_social_importador'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover índices apenas se existirem
    if index_exists('operacoes_comex', 'ix_operacoes_comex_razao_social_importador'):
        op.drop_index(op.f('ix_operacoes_comex_razao_social_importador'), table_name='operacoes_comex')
    if index_exists('operacoes_comex', 'ix_operacoes_comex_razao_social_exportador'):
        op.drop_index(op.f('ix_operacoes_comex_razao_social_exportador'), table_name='operacoes_comex')
    if index_exists('operacoes_comex', 'ix_operacoes_comex_cnpj_importador'):
        op.drop_index(op.f('ix_operacoes_comex_cnpj_importador'), table_name='operacoes_comex')
    if index_exists('operacoes_comex', 'ix_operacoes_comex_cnpj_exportador'):
        op.drop_index(op.f('ix_operacoes_comex_cnpj_exportador'), table_name='operacoes_comex')
    
    # Alterar colunas de volta (pode falhar se já estiverem no formato antigo)
    try:
        op.alter_column('operacoes_comex', 'razao_social_exportador',
                   existing_type=sa.String(length=255),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    except Exception:
        pass
    
    try:
        op.alter_column('operacoes_comex', 'razao_social_importador',
                   existing_type=sa.String(length=255),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    except Exception:
        pass
    # ### end Alembic commands ###
