"""create initial tables

Revision ID: de31743c9111
Revises: 
Create Date: 2026-01-11 17:40:18.055794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de31743c9111'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alterar colunas apenas se necessário (pode falhar se já foram alteradas)
    try:
        op.alter_column('operacoes_comex', 'razao_social_importador',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    except Exception:
        pass  # Coluna já pode estar no formato correto
    
    try:
        op.alter_column('operacoes_comex', 'razao_social_exportador',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    except Exception:
        pass  # Coluna já pode estar no formato correto
    
    # Criar índices apenas se não existirem (usando try/except para evitar erros)
    try:
        op.create_index(op.f('ix_operacoes_comex_cnpj_exportador'), 'operacoes_comex', ['cnpj_exportador'], unique=False)
    except Exception:
        pass  # Índice já existe
    
    try:
        op.create_index(op.f('ix_operacoes_comex_cnpj_importador'), 'operacoes_comex', ['cnpj_importador'], unique=False)
    except Exception:
        pass  # Índice já existe
    
    try:
        op.create_index(op.f('ix_operacoes_comex_razao_social_exportador'), 'operacoes_comex', ['razao_social_exportador'], unique=False)
    except Exception:
        pass  # Índice já existe
    
    try:
        op.create_index(op.f('ix_operacoes_comex_razao_social_importador'), 'operacoes_comex', ['razao_social_importador'], unique=False)
    except Exception:
        pass  # Índice já existe
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover índices (usando try/except para evitar erros se não existirem)
    try:
        op.drop_index(op.f('ix_operacoes_comex_razao_social_importador'), table_name='operacoes_comex')
    except Exception:
        pass  # Índice não existe
    
    try:
        op.drop_index(op.f('ix_operacoes_comex_razao_social_exportador'), table_name='operacoes_comex')
    except Exception:
        pass  # Índice não existe
    
    try:
        op.drop_index(op.f('ix_operacoes_comex_cnpj_importador'), table_name='operacoes_comex')
    except Exception:
        pass  # Índice não existe
    
    try:
        op.drop_index(op.f('ix_operacoes_comex_cnpj_exportador'), table_name='operacoes_comex')
    except Exception:
        pass  # Índice não existe
    
    # Alterar colunas de volta (pode falhar se já estiverem no formato antigo)
    try:
        op.alter_column('operacoes_comex', 'razao_social_exportador',
                   existing_type=sa.String(length=255),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    except Exception:
        pass
    
    try:
        op.alter_column('operacoes_comex', 'razao_social_importador',
                   existing_type=sa.String(length=255),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    except Exception:
        pass
    # ### end Alembic commands ###
